# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'block_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_block_form(object):
    def setupUi(self, block_form):
        block_form.setObjectName("block_form")
        block_form.resize(461, 129)
        self.gridLayout = QtWidgets.QGridLayout(block_form)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(3, -1, -1, -1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.radioButton = QtWidgets.QRadioButton(block_form)
        self.radioButton.setObjectName("radioButton")
        self.verticalLayout.addWidget(self.radioButton)
        self.radioButton_2 = QtWidgets.QRadioButton(block_form)
        self.radioButton_2.setObjectName("radioButton_2")
        self.verticalLayout.addWidget(self.radioButton_2)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.label = QtWidgets.QLabel(block_form)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 1, 1, 1)
        self.comboBox = QtWidgets.QComboBox(block_form)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.gridLayout.addWidget(self.comboBox, 0, 2, 1, 1)
        self.pushButton = QtWidgets.QPushButton(block_form)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 1, 0, 1, 3)

        self.retranslateUi(block_form)
        QtCore.QMetaObject.connectSlotsByName(block_form)

    def retranslateUi(self, block_form):
        _translate = QtCore.QCoreApplication.translate
        block_form.setWindowTitle(_translate("block_form", "Окно блокировки"))
        self.radioButton.setText(_translate("block_form", "Заблокировать IP"))
        self.radioButton_2.setText(_translate("block_form", "Заблокировать пользователя"))
        self.label.setText(_translate("block_form", "Время блокировки"))
        self.comboBox.setItemText(0, _translate("block_form", "15 минут"))
        self.comboBox.setItemText(1, _translate("block_form", "30 минут"))
        self.comboBox.setItemText(2, _translate("block_form", "1 час"))
        self.comboBox.setItemText(3, _translate("block_form", "4 часа"))
        self.comboBox.setItemText(4, _translate("block_form", "12 часов"))
        self.comboBox.setItemText(5, _translate("block_form", "1 день"))
        self.comboBox.setItemText(6, _translate("block_form", "7 дней"))
        self.comboBox.setItemText(7, _translate("block_form", "Навсегда"))
        self.pushButton.setText(_translate("block_form", "Заблокировать"))
